server: 
  port: 9004
spring: 
  application:  
    name: tensquare_qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.99.136.0:3306/tensquare_qa?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
    generate-ddl: true
