spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/614015759/tensquare-config.git



server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6869/eureka

management:  #暴露触发消息总线的地址
  endpoints:
    jmx:
      exposure:
        include: bus-refresh